### ISSUE TITLE
STIX spec and best practices validator apparently disagree on STIX header title field

### ISSUE THREAD

**Issue by megahall** [STIXProject/stix-validator#67]
According to this page the title for the STIX header seems to be deprecated:

http://stix.readthedocs.org/en/latest/api/core/stix_header.html

But the error still happens in the best practices validation:

        [!] Missing Titles
            [-] line : 15
            [-] message : None
            [-] id : None
            [-] idref : None
            [-] tag : {http://stix.mitre.org/stix-1}STIX_Header

I am just trying to understand: what should one do to get this part right?

**Comment by bworrell** [comment]
@megahall, what version is the STIX document you are validating and what version of the stix-validator are you using? The `Title` in `STIX_Header` became deprecated in STIX v1.2, but was actually a  suggested practice in previous versions. Because of this, the stix-validator will (read: should) report a warning if the `Title` is missing on a STIX v1.1.1 (or prior) document, and report a warning if it's found on a STIX v1.2 document.  This behavior was implemented in v2.2.0 of the stix-validator. All of this said, there may still be a bug in the stix-validator :)

**Comment by megahall** [comment]
It looks like a STIX 1.1.1 document, so this makes sense. Thanks for explaining it!

**Comment by bworrell** [comment]
I am going to close this since everything seems to have been resolved :)
