### ISSUE TITLE
Validate a string document

### ISSUE THREAD

**Issue by cyberfox1** [STIXProject/stix-validator#82]
The core validation code seems only to deal with a filname (fn).

It would be nice if there was an option to pass the document as a string rather than a filename, like e.g. the stix-elevator which has an elevate_string() function.

**Comment by gtback** [comment]
Hi @cyberfox1 . You should be able to pass in a `StringIO` class instead of a filename. 

> This can be a filename, file-like object, etree._Element or etree._ElementTree object.

https://stix-validator.readthedocs.io/en/stable/api/sdv.html#sdv.validate_xml

In this case, `StringIO` is a "file-like object", since it implements the `read` method that `etree.parse` needs: https://github.com/STIXProject/stix-validator/blob/master/sdv/utils.py#L107

Let me know if that doesn't work. We may just need to document it better.

**Comment by cyberfox1** [comment]
@gtback thanks, I was looking at the source code and missed the documentation and thought it only accepted a filename. Cheers.
